### model
model_name_or_path: /path/to/Qwen/base/model
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: ds_config.json

### dataset
dataset: SWE-Play/SWE-Play-mix
template: qwen
cutoff_len: 128000
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/SWE-Play-mix
logging_steps: 10
save_steps: 704
plot_loss: true
overwrite_output_dir: true

### train
flash_attn: fa2
enable_liger_kernel: true
use_unsloth_gc: true
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-5
num_train_epochs: 5.0
lr_scheduler_type: cosine
warmup_ratio: 0.05
bf16: true
ddp_timeout: 180000000

### wandb
report_to: wandb
run_name: SWE-Playp-mix